apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.debug.yml --out kube.debug.yml
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: demo
      name: demo
    spec:
      ports:
        - name: "3000"
          port: 3000
          targetPort: 3000
        - name: "9229"
          port: 9229
          targetPort: 9229
      selector:
        io.kompose.service: demo
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.debug.yml --out kube.debug.yml
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: demo
      name: demo
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: demo
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.debug.yml --out kube.debug.yml
            kompose.version: 1.26.0 (HEAD)
          creationTimestamp: null
          labels:
            io.kompose.service: demo
        spec:
          containers:
            - args:
                - node
                - --inspect=0.0.0.0:9229
                - ./bin/www
              env:
                - name: NODE_ENV
                  value: development
              image: demo
              name: demo
              ports:
                - containerPort: 3000
                - containerPort: 9229
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}

