// private java.lang.String hostname; // required
// private java.lang.String ip; // required
// private java.lang.String ports; // required
// private java.lang.String agentId; // required
// private java.lang.String applicationName; // required
// private short serviceType; // required
// private int pid; // required
// private java.lang.String agentVersion; // required
// private java.lang.String vmVersion; // required
// private long startTimestamp; // required
// private long endTimestamp; // optional
// private int endStatus; // optional
// private TServerMetaData serverMetaData; // optional
// private TJvmInfo jvmInfo; // optional
// private boolean container; // optional