// private long spanId; // optional
// private short sequence; // required
// private int startElapsed; // required
// private int endElapsed; // optional
// private java.lang.String rpc; // optional
// private short serviceType; // required
// private java.lang.String endPoint; // optional
// private java.util.List<TAnnotation> annotations; // optional
// private int depth; // optional
// private long nextSpanId; // optional
// private java.lang.String destinationId; // optional
// private int apiId; // optional
// private TIntStringValue exceptionInfo; // optional
// private int asyncId; // optional
// private int nextAsyncId; // optional
// private short asyncSequence; // optional
