// private java.lang.String agentId; // required
// private java.lang.String applicationName; // required
// private long agentStartTime; // required
// private java.nio.ByteBuffer transactionId; // required
// private long spanId; // required
// private long parentSpanId; // optional
// private long startTime; // required
// private int elapsed; // optional
// private java.lang.String rpc; // optional
// private short serviceType; // required
// private java.lang.String endPoint; // optional
// private java.lang.String remoteAddr; // optional
// private java.util.List<TAnnotation> annotations; // optional
// private short flag; // optional
// private int err; // optional
// private java.util.List<TSpanEvent> spanEventList; // optional
// private java.lang.String parentApplicationName; // optional
// private short parentApplicationType; // optional
// private java.lang.String acceptorHost; // optional
// private int apiId; // optional
// private TIntStringValue exceptionInfo; // optional
// private short applicationServiceType; // optional
// private byte loggingTransactionInfo; // optional
// private byte version; // optional