//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


TJvmGcType = {
  'UNKNOWN' : 0,
  'SERIAL' : 1,
  'PARALLEL' : 2,
  'CMS' : 3,
  'G1' : 4
};
TServiceInfo = function(args) {
  this.serviceName = null;
  this.serviceLibs = null;
  if (args) {
    if (args.serviceName !== undefined && args.serviceName !== null) {
      this.serviceName = args.serviceName;
    }
    if (args.serviceLibs !== undefined && args.serviceLibs !== null) {
      this.serviceLibs = Thrift.copyList(args.serviceLibs, [null]);
    }
  }
};
TServiceInfo.prototype = {};
TServiceInfo.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.serviceName = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.serviceLibs = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = input.readString().value;
          this.serviceLibs.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TServiceInfo.prototype.write = function(output) {
  output.writeStructBegin('TServiceInfo');
  if (this.serviceName !== null && this.serviceName !== undefined) {
    output.writeFieldBegin('serviceName', Thrift.Type.STRING, 1);
    output.writeString(this.serviceName);
    output.writeFieldEnd();
  }
  if (this.serviceLibs !== null && this.serviceLibs !== undefined) {
    output.writeFieldBegin('serviceLibs', Thrift.Type.LIST, 2);
    output.writeListBegin(Thrift.Type.STRING, this.serviceLibs.length);
    for (var iter7 in this.serviceLibs)
    {
      if (this.serviceLibs.hasOwnProperty(iter7))
      {
        iter7 = this.serviceLibs[iter7];
        output.writeString(iter7);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TServerMetaData = function(args) {
  this.serverInfo = null;
  this.vmArgs = null;
  this.serviceInfos = null;
  if (args) {
    if (args.serverInfo !== undefined && args.serverInfo !== null) {
      this.serverInfo = args.serverInfo;
    }
    if (args.vmArgs !== undefined && args.vmArgs !== null) {
      this.vmArgs = Thrift.copyList(args.vmArgs, [null]);
    }
    if (args.serviceInfos !== undefined && args.serviceInfos !== null) {
      this.serviceInfos = Thrift.copyList(args.serviceInfos, [TServiceInfo]);
    }
  }
};
TServerMetaData.prototype = {};
TServerMetaData.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.serverInfo = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.LIST) {
        var _size8 = 0;
        var _rtmp312;
        this.vmArgs = [];
        var _etype11 = 0;
        _rtmp312 = input.readListBegin();
        _etype11 = _rtmp312.etype;
        _size8 = _rtmp312.size;
        for (var _i13 = 0; _i13 < _size8; ++_i13)
        {
          var elem14 = null;
          elem14 = input.readString().value;
          this.vmArgs.push(elem14);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 10:
      if (ftype == Thrift.Type.LIST) {
        var _size15 = 0;
        var _rtmp319;
        this.serviceInfos = [];
        var _etype18 = 0;
        _rtmp319 = input.readListBegin();
        _etype18 = _rtmp319.etype;
        _size15 = _rtmp319.size;
        for (var _i20 = 0; _i20 < _size15; ++_i20)
        {
          var elem21 = null;
          elem21 = new TServiceInfo();
          elem21.read(input);
          this.serviceInfos.push(elem21);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TServerMetaData.prototype.write = function(output) {
  output.writeStructBegin('TServerMetaData');
  if (this.serverInfo !== null && this.serverInfo !== undefined) {
    output.writeFieldBegin('serverInfo', Thrift.Type.STRING, 1);
    output.writeString(this.serverInfo);
    output.writeFieldEnd();
  }
  if (this.vmArgs !== null && this.vmArgs !== undefined) {
    output.writeFieldBegin('vmArgs', Thrift.Type.LIST, 2);
    output.writeListBegin(Thrift.Type.STRING, this.vmArgs.length);
    for (var iter22 in this.vmArgs)
    {
      if (this.vmArgs.hasOwnProperty(iter22))
      {
        iter22 = this.vmArgs[iter22];
        output.writeString(iter22);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.serviceInfos !== null && this.serviceInfos !== undefined) {
    output.writeFieldBegin('serviceInfos', Thrift.Type.LIST, 10);
    output.writeListBegin(Thrift.Type.STRUCT, this.serviceInfos.length);
    for (var iter23 in this.serviceInfos)
    {
      if (this.serviceInfos.hasOwnProperty(iter23))
      {
        iter23 = this.serviceInfos[iter23];
        iter23.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TJvmInfo = function(args) {
  this.version = 0;
  this.vmVersion = null;
  this.gcType = 0;
  if (args) {
    if (args.version !== undefined && args.version !== null) {
      this.version = args.version;
    }
    if (args.vmVersion !== undefined && args.vmVersion !== null) {
      this.vmVersion = args.vmVersion;
    }
    if (args.gcType !== undefined && args.gcType !== null) {
      this.gcType = args.gcType;
    }
  }
};
TJvmInfo.prototype = {};
TJvmInfo.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I16) {
        this.version = input.readI16().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.vmVersion = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.gcType = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TJvmInfo.prototype.write = function(output) {
  output.writeStructBegin('TJvmInfo');
  if (this.version !== null && this.version !== undefined) {
    output.writeFieldBegin('version', Thrift.Type.I16, 1);
    output.writeI16(this.version);
    output.writeFieldEnd();
  }
  if (this.vmVersion !== null && this.vmVersion !== undefined) {
    output.writeFieldBegin('vmVersion', Thrift.Type.STRING, 2);
    output.writeString(this.vmVersion);
    output.writeFieldEnd();
  }
  if (this.gcType !== null && this.gcType !== undefined) {
    output.writeFieldBegin('gcType', Thrift.Type.I32, 3);
    output.writeI32(this.gcType);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TAgentInfo = function(args) {
  this.hostname = null;
  this.ip = null;
  this.ports = null;
  this.agentId = null;
  this.applicationName = null;
  this.serviceType = null;
  this.pid = null;
  this.agentVersion = null;
  this.vmVersion = null;
  this.startTimestamp = null;
  this.endTimestamp = null;
  this.endStatus = null;
  this.serverMetaData = null;
  this.jvmInfo = null;
  this.container = false;
  if (args) {
    if (args.hostname !== undefined && args.hostname !== null) {
      this.hostname = args.hostname;
    }
    if (args.ip !== undefined && args.ip !== null) {
      this.ip = args.ip;
    }
    if (args.ports !== undefined && args.ports !== null) {
      this.ports = args.ports;
    }
    if (args.agentId !== undefined && args.agentId !== null) {
      this.agentId = args.agentId;
    }
    if (args.applicationName !== undefined && args.applicationName !== null) {
      this.applicationName = args.applicationName;
    }
    if (args.serviceType !== undefined && args.serviceType !== null) {
      this.serviceType = args.serviceType;
    }
    if (args.pid !== undefined && args.pid !== null) {
      this.pid = args.pid;
    }
    if (args.agentVersion !== undefined && args.agentVersion !== null) {
      this.agentVersion = args.agentVersion;
    }
    if (args.vmVersion !== undefined && args.vmVersion !== null) {
      this.vmVersion = args.vmVersion;
    }
    if (args.startTimestamp !== undefined && args.startTimestamp !== null) {
      this.startTimestamp = args.startTimestamp;
    }
    if (args.endTimestamp !== undefined && args.endTimestamp !== null) {
      this.endTimestamp = args.endTimestamp;
    }
    if (args.endStatus !== undefined && args.endStatus !== null) {
      this.endStatus = args.endStatus;
    }
    if (args.serverMetaData !== undefined && args.serverMetaData !== null) {
      this.serverMetaData = new TServerMetaData(args.serverMetaData);
    }
    if (args.jvmInfo !== undefined && args.jvmInfo !== null) {
      this.jvmInfo = new TJvmInfo(args.jvmInfo);
    }
    if (args.container !== undefined && args.container !== null) {
      this.container = args.container;
    }
  }
};
TAgentInfo.prototype = {};
TAgentInfo.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.hostname = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.ip = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.ports = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.agentId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.applicationName = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.I16) {
        this.serviceType = input.readI16().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.I32) {
        this.pid = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 8:
      if (ftype == Thrift.Type.STRING) {
        this.agentVersion = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 9:
      if (ftype == Thrift.Type.STRING) {
        this.vmVersion = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 10:
      if (ftype == Thrift.Type.I64) {
        this.startTimestamp = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 11:
      if (ftype == Thrift.Type.I64) {
        this.endTimestamp = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 12:
      if (ftype == Thrift.Type.I32) {
        this.endStatus = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 20:
      if (ftype == Thrift.Type.STRUCT) {
        this.serverMetaData = new TServerMetaData();
        this.serverMetaData.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 30:
      if (ftype == Thrift.Type.STRUCT) {
        this.jvmInfo = new TJvmInfo();
        this.jvmInfo.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 40:
      if (ftype == Thrift.Type.BOOL) {
        this.container = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TAgentInfo.prototype.write = function(output) {
  output.writeStructBegin('TAgentInfo');
  if (this.hostname !== null && this.hostname !== undefined) {
    output.writeFieldBegin('hostname', Thrift.Type.STRING, 1);
    output.writeString(this.hostname);
    output.writeFieldEnd();
  }
  if (this.ip !== null && this.ip !== undefined) {
    output.writeFieldBegin('ip', Thrift.Type.STRING, 2);
    output.writeString(this.ip);
    output.writeFieldEnd();
  }
  if (this.ports !== null && this.ports !== undefined) {
    output.writeFieldBegin('ports', Thrift.Type.STRING, 3);
    output.writeString(this.ports);
    output.writeFieldEnd();
  }
  if (this.agentId !== null && this.agentId !== undefined) {
    output.writeFieldBegin('agentId', Thrift.Type.STRING, 4);
    output.writeString(this.agentId);
    output.writeFieldEnd();
  }
  if (this.applicationName !== null && this.applicationName !== undefined) {
    output.writeFieldBegin('applicationName', Thrift.Type.STRING, 5);
    output.writeString(this.applicationName);
    output.writeFieldEnd();
  }
  if (this.serviceType !== null && this.serviceType !== undefined) {
    output.writeFieldBegin('serviceType', Thrift.Type.I16, 6);
    output.writeI16(this.serviceType);
    output.writeFieldEnd();
  }
  if (this.pid !== null && this.pid !== undefined) {
    output.writeFieldBegin('pid', Thrift.Type.I32, 7);
    output.writeI32(this.pid);
    output.writeFieldEnd();
  }
  if (this.agentVersion !== null && this.agentVersion !== undefined) {
    output.writeFieldBegin('agentVersion', Thrift.Type.STRING, 8);
    output.writeString(this.agentVersion);
    output.writeFieldEnd();
  }
  if (this.vmVersion !== null && this.vmVersion !== undefined) {
    output.writeFieldBegin('vmVersion', Thrift.Type.STRING, 9);
    output.writeString(this.vmVersion);
    output.writeFieldEnd();
  }
  if (this.startTimestamp !== null && this.startTimestamp !== undefined) {
    output.writeFieldBegin('startTimestamp', Thrift.Type.I64, 10);
    output.writeI64(this.startTimestamp);
    output.writeFieldEnd();
  }
  if (this.endTimestamp !== null && this.endTimestamp !== undefined) {
    output.writeFieldBegin('endTimestamp', Thrift.Type.I64, 11);
    output.writeI64(this.endTimestamp);
    output.writeFieldEnd();
  }
  if (this.endStatus !== null && this.endStatus !== undefined) {
    output.writeFieldBegin('endStatus', Thrift.Type.I32, 12);
    output.writeI32(this.endStatus);
    output.writeFieldEnd();
  }
  if (this.serverMetaData !== null && this.serverMetaData !== undefined) {
    output.writeFieldBegin('serverMetaData', Thrift.Type.STRUCT, 20);
    this.serverMetaData.write(output);
    output.writeFieldEnd();
  }
  if (this.jvmInfo !== null && this.jvmInfo !== undefined) {
    output.writeFieldBegin('jvmInfo', Thrift.Type.STRUCT, 30);
    this.jvmInfo.write(output);
    output.writeFieldEnd();
  }
  if (this.container !== null && this.container !== undefined) {
    output.writeFieldBegin('container', Thrift.Type.BOOL, 40);
    output.writeBool(this.container);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TJvmGc = function(args) {
  this.type = 0;
  this.jvmMemoryHeapUsed = null;
  this.jvmMemoryHeapMax = null;
  this.jvmMemoryNonHeapUsed = null;
  this.jvmMemoryNonHeapMax = null;
  this.jvmGcOldCount = null;
  this.jvmGcOldTime = null;
  this.jvmGcDetailed = null;
  if (args) {
    if (args.type !== undefined && args.type !== null) {
      this.type = args.type;
    }
    if (args.jvmMemoryHeapUsed !== undefined && args.jvmMemoryHeapUsed !== null) {
      this.jvmMemoryHeapUsed = args.jvmMemoryHeapUsed;
    }
    if (args.jvmMemoryHeapMax !== undefined && args.jvmMemoryHeapMax !== null) {
      this.jvmMemoryHeapMax = args.jvmMemoryHeapMax;
    }
    if (args.jvmMemoryNonHeapUsed !== undefined && args.jvmMemoryNonHeapUsed !== null) {
      this.jvmMemoryNonHeapUsed = args.jvmMemoryNonHeapUsed;
    }
    if (args.jvmMemoryNonHeapMax !== undefined && args.jvmMemoryNonHeapMax !== null) {
      this.jvmMemoryNonHeapMax = args.jvmMemoryNonHeapMax;
    }
    if (args.jvmGcOldCount !== undefined && args.jvmGcOldCount !== null) {
      this.jvmGcOldCount = args.jvmGcOldCount;
    }
    if (args.jvmGcOldTime !== undefined && args.jvmGcOldTime !== null) {
      this.jvmGcOldTime = args.jvmGcOldTime;
    }
    if (args.jvmGcDetailed !== undefined && args.jvmGcDetailed !== null) {
      this.jvmGcDetailed = new TJvmGcDetailed(args.jvmGcDetailed);
    }
  }
};
TJvmGc.prototype = {};
TJvmGc.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.type = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.jvmMemoryHeapUsed = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I64) {
        this.jvmMemoryHeapMax = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I64) {
        this.jvmMemoryNonHeapUsed = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.I64) {
        this.jvmMemoryNonHeapMax = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.I64) {
        this.jvmGcOldCount = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.I64) {
        this.jvmGcOldTime = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 8:
      if (ftype == Thrift.Type.STRUCT) {
        this.jvmGcDetailed = new TJvmGcDetailed();
        this.jvmGcDetailed.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TJvmGc.prototype.write = function(output) {
  output.writeStructBegin('TJvmGc');
  if (this.type !== null && this.type !== undefined) {
    output.writeFieldBegin('type', Thrift.Type.I32, 1);
    output.writeI32(this.type);
    output.writeFieldEnd();
  }
  if (this.jvmMemoryHeapUsed !== null && this.jvmMemoryHeapUsed !== undefined) {
    output.writeFieldBegin('jvmMemoryHeapUsed', Thrift.Type.I64, 2);
    output.writeI64(this.jvmMemoryHeapUsed);
    output.writeFieldEnd();
  }
  if (this.jvmMemoryHeapMax !== null && this.jvmMemoryHeapMax !== undefined) {
    output.writeFieldBegin('jvmMemoryHeapMax', Thrift.Type.I64, 3);
    output.writeI64(this.jvmMemoryHeapMax);
    output.writeFieldEnd();
  }
  if (this.jvmMemoryNonHeapUsed !== null && this.jvmMemoryNonHeapUsed !== undefined) {
    output.writeFieldBegin('jvmMemoryNonHeapUsed', Thrift.Type.I64, 4);
    output.writeI64(this.jvmMemoryNonHeapUsed);
    output.writeFieldEnd();
  }
  if (this.jvmMemoryNonHeapMax !== null && this.jvmMemoryNonHeapMax !== undefined) {
    output.writeFieldBegin('jvmMemoryNonHeapMax', Thrift.Type.I64, 5);
    output.writeI64(this.jvmMemoryNonHeapMax);
    output.writeFieldEnd();
  }
  if (this.jvmGcOldCount !== null && this.jvmGcOldCount !== undefined) {
    output.writeFieldBegin('jvmGcOldCount', Thrift.Type.I64, 6);
    output.writeI64(this.jvmGcOldCount);
    output.writeFieldEnd();
  }
  if (this.jvmGcOldTime !== null && this.jvmGcOldTime !== undefined) {
    output.writeFieldBegin('jvmGcOldTime', Thrift.Type.I64, 7);
    output.writeI64(this.jvmGcOldTime);
    output.writeFieldEnd();
  }
  if (this.jvmGcDetailed !== null && this.jvmGcDetailed !== undefined) {
    output.writeFieldBegin('jvmGcDetailed', Thrift.Type.STRUCT, 8);
    this.jvmGcDetailed.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TDirectBuffer = function(args) {
  this.directCount = null;
  this.directMemoryUsed = null;
  this.mappedCount = null;
  this.mappedMemoryUsed = null;
  if (args) {
    if (args.directCount !== undefined && args.directCount !== null) {
      this.directCount = args.directCount;
    }
    if (args.directMemoryUsed !== undefined && args.directMemoryUsed !== null) {
      this.directMemoryUsed = args.directMemoryUsed;
    }
    if (args.mappedCount !== undefined && args.mappedCount !== null) {
      this.mappedCount = args.mappedCount;
    }
    if (args.mappedMemoryUsed !== undefined && args.mappedMemoryUsed !== null) {
      this.mappedMemoryUsed = args.mappedMemoryUsed;
    }
  }
};
TDirectBuffer.prototype = {};
TDirectBuffer.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I64) {
        this.directCount = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.directMemoryUsed = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I64) {
        this.mappedCount = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I64) {
        this.mappedMemoryUsed = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TDirectBuffer.prototype.write = function(output) {
  output.writeStructBegin('TDirectBuffer');
  if (this.directCount !== null && this.directCount !== undefined) {
    output.writeFieldBegin('directCount', Thrift.Type.I64, 1);
    output.writeI64(this.directCount);
    output.writeFieldEnd();
  }
  if (this.directMemoryUsed !== null && this.directMemoryUsed !== undefined) {
    output.writeFieldBegin('directMemoryUsed', Thrift.Type.I64, 2);
    output.writeI64(this.directMemoryUsed);
    output.writeFieldEnd();
  }
  if (this.mappedCount !== null && this.mappedCount !== undefined) {
    output.writeFieldBegin('mappedCount', Thrift.Type.I64, 3);
    output.writeI64(this.mappedCount);
    output.writeFieldEnd();
  }
  if (this.mappedMemoryUsed !== null && this.mappedMemoryUsed !== undefined) {
    output.writeFieldBegin('mappedMemoryUsed', Thrift.Type.I64, 4);
    output.writeI64(this.mappedMemoryUsed);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TJvmGcDetailed = function(args) {
  this.jvmGcNewCount = null;
  this.jvmGcNewTime = null;
  this.jvmPoolCodeCacheUsed = null;
  this.jvmPoolNewGenUsed = null;
  this.jvmPoolOldGenUsed = null;
  this.jvmPoolSurvivorSpaceUsed = null;
  this.jvmPoolPermGenUsed = null;
  this.jvmPoolMetaspaceUsed = null;
  if (args) {
    if (args.jvmGcNewCount !== undefined && args.jvmGcNewCount !== null) {
      this.jvmGcNewCount = args.jvmGcNewCount;
    }
    if (args.jvmGcNewTime !== undefined && args.jvmGcNewTime !== null) {
      this.jvmGcNewTime = args.jvmGcNewTime;
    }
    if (args.jvmPoolCodeCacheUsed !== undefined && args.jvmPoolCodeCacheUsed !== null) {
      this.jvmPoolCodeCacheUsed = args.jvmPoolCodeCacheUsed;
    }
    if (args.jvmPoolNewGenUsed !== undefined && args.jvmPoolNewGenUsed !== null) {
      this.jvmPoolNewGenUsed = args.jvmPoolNewGenUsed;
    }
    if (args.jvmPoolOldGenUsed !== undefined && args.jvmPoolOldGenUsed !== null) {
      this.jvmPoolOldGenUsed = args.jvmPoolOldGenUsed;
    }
    if (args.jvmPoolSurvivorSpaceUsed !== undefined && args.jvmPoolSurvivorSpaceUsed !== null) {
      this.jvmPoolSurvivorSpaceUsed = args.jvmPoolSurvivorSpaceUsed;
    }
    if (args.jvmPoolPermGenUsed !== undefined && args.jvmPoolPermGenUsed !== null) {
      this.jvmPoolPermGenUsed = args.jvmPoolPermGenUsed;
    }
    if (args.jvmPoolMetaspaceUsed !== undefined && args.jvmPoolMetaspaceUsed !== null) {
      this.jvmPoolMetaspaceUsed = args.jvmPoolMetaspaceUsed;
    }
  }
};
TJvmGcDetailed.prototype = {};
TJvmGcDetailed.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I64) {
        this.jvmGcNewCount = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.jvmGcNewTime = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.DOUBLE) {
        this.jvmPoolCodeCacheUsed = input.readDouble().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.DOUBLE) {
        this.jvmPoolNewGenUsed = input.readDouble().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.DOUBLE) {
        this.jvmPoolOldGenUsed = input.readDouble().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.DOUBLE) {
        this.jvmPoolSurvivorSpaceUsed = input.readDouble().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.DOUBLE) {
        this.jvmPoolPermGenUsed = input.readDouble().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 8:
      if (ftype == Thrift.Type.DOUBLE) {
        this.jvmPoolMetaspaceUsed = input.readDouble().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TJvmGcDetailed.prototype.write = function(output) {
  output.writeStructBegin('TJvmGcDetailed');
  if (this.jvmGcNewCount !== null && this.jvmGcNewCount !== undefined) {
    output.writeFieldBegin('jvmGcNewCount', Thrift.Type.I64, 1);
    output.writeI64(this.jvmGcNewCount);
    output.writeFieldEnd();
  }
  if (this.jvmGcNewTime !== null && this.jvmGcNewTime !== undefined) {
    output.writeFieldBegin('jvmGcNewTime', Thrift.Type.I64, 2);
    output.writeI64(this.jvmGcNewTime);
    output.writeFieldEnd();
  }
  if (this.jvmPoolCodeCacheUsed !== null && this.jvmPoolCodeCacheUsed !== undefined) {
    output.writeFieldBegin('jvmPoolCodeCacheUsed', Thrift.Type.DOUBLE, 3);
    output.writeDouble(this.jvmPoolCodeCacheUsed);
    output.writeFieldEnd();
  }
  if (this.jvmPoolNewGenUsed !== null && this.jvmPoolNewGenUsed !== undefined) {
    output.writeFieldBegin('jvmPoolNewGenUsed', Thrift.Type.DOUBLE, 4);
    output.writeDouble(this.jvmPoolNewGenUsed);
    output.writeFieldEnd();
  }
  if (this.jvmPoolOldGenUsed !== null && this.jvmPoolOldGenUsed !== undefined) {
    output.writeFieldBegin('jvmPoolOldGenUsed', Thrift.Type.DOUBLE, 5);
    output.writeDouble(this.jvmPoolOldGenUsed);
    output.writeFieldEnd();
  }
  if (this.jvmPoolSurvivorSpaceUsed !== null && this.jvmPoolSurvivorSpaceUsed !== undefined) {
    output.writeFieldBegin('jvmPoolSurvivorSpaceUsed', Thrift.Type.DOUBLE, 6);
    output.writeDouble(this.jvmPoolSurvivorSpaceUsed);
    output.writeFieldEnd();
  }
  if (this.jvmPoolPermGenUsed !== null && this.jvmPoolPermGenUsed !== undefined) {
    output.writeFieldBegin('jvmPoolPermGenUsed', Thrift.Type.DOUBLE, 7);
    output.writeDouble(this.jvmPoolPermGenUsed);
    output.writeFieldEnd();
  }
  if (this.jvmPoolMetaspaceUsed !== null && this.jvmPoolMetaspaceUsed !== undefined) {
    output.writeFieldBegin('jvmPoolMetaspaceUsed', Thrift.Type.DOUBLE, 8);
    output.writeDouble(this.jvmPoolMetaspaceUsed);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TCpuLoad = function(args) {
  this.jvmCpuLoad = null;
  this.systemCpuLoad = null;
  if (args) {
    if (args.jvmCpuLoad !== undefined && args.jvmCpuLoad !== null) {
      this.jvmCpuLoad = args.jvmCpuLoad;
    }
    if (args.systemCpuLoad !== undefined && args.systemCpuLoad !== null) {
      this.systemCpuLoad = args.systemCpuLoad;
    }
  }
};
TCpuLoad.prototype = {};
TCpuLoad.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.DOUBLE) {
        this.jvmCpuLoad = input.readDouble().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.DOUBLE) {
        this.systemCpuLoad = input.readDouble().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TCpuLoad.prototype.write = function(output) {
  output.writeStructBegin('TCpuLoad');
  if (this.jvmCpuLoad !== null && this.jvmCpuLoad !== undefined) {
    output.writeFieldBegin('jvmCpuLoad', Thrift.Type.DOUBLE, 1);
    output.writeDouble(this.jvmCpuLoad);
    output.writeFieldEnd();
  }
  if (this.systemCpuLoad !== null && this.systemCpuLoad !== undefined) {
    output.writeFieldBegin('systemCpuLoad', Thrift.Type.DOUBLE, 2);
    output.writeDouble(this.systemCpuLoad);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TTransaction = function(args) {
  this.sampledNewCount = null;
  this.sampledContinuationCount = null;
  this.unsampledNewCount = null;
  this.unsampledContinuationCount = null;
  if (args) {
    if (args.sampledNewCount !== undefined && args.sampledNewCount !== null) {
      this.sampledNewCount = args.sampledNewCount;
    }
    if (args.sampledContinuationCount !== undefined && args.sampledContinuationCount !== null) {
      this.sampledContinuationCount = args.sampledContinuationCount;
    }
    if (args.unsampledNewCount !== undefined && args.unsampledNewCount !== null) {
      this.unsampledNewCount = args.unsampledNewCount;
    }
    if (args.unsampledContinuationCount !== undefined && args.unsampledContinuationCount !== null) {
      this.unsampledContinuationCount = args.unsampledContinuationCount;
    }
  }
};
TTransaction.prototype = {};
TTransaction.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.sampledNewCount = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I64) {
        this.sampledContinuationCount = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I64) {
        this.unsampledNewCount = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.I64) {
        this.unsampledContinuationCount = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TTransaction.prototype.write = function(output) {
  output.writeStructBegin('TTransaction');
  if (this.sampledNewCount !== null && this.sampledNewCount !== undefined) {
    output.writeFieldBegin('sampledNewCount', Thrift.Type.I64, 2);
    output.writeI64(this.sampledNewCount);
    output.writeFieldEnd();
  }
  if (this.sampledContinuationCount !== null && this.sampledContinuationCount !== undefined) {
    output.writeFieldBegin('sampledContinuationCount', Thrift.Type.I64, 3);
    output.writeI64(this.sampledContinuationCount);
    output.writeFieldEnd();
  }
  if (this.unsampledNewCount !== null && this.unsampledNewCount !== undefined) {
    output.writeFieldBegin('unsampledNewCount', Thrift.Type.I64, 4);
    output.writeI64(this.unsampledNewCount);
    output.writeFieldEnd();
  }
  if (this.unsampledContinuationCount !== null && this.unsampledContinuationCount !== undefined) {
    output.writeFieldBegin('unsampledContinuationCount', Thrift.Type.I64, 5);
    output.writeI64(this.unsampledContinuationCount);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TActiveTraceHistogram = function(args) {
  this.version = 0;
  this.histogramSchemaType = null;
  this.activeTraceCount = null;
  if (args) {
    if (args.version !== undefined && args.version !== null) {
      this.version = args.version;
    }
    if (args.histogramSchemaType !== undefined && args.histogramSchemaType !== null) {
      this.histogramSchemaType = args.histogramSchemaType;
    }
    if (args.activeTraceCount !== undefined && args.activeTraceCount !== null) {
      this.activeTraceCount = Thrift.copyList(args.activeTraceCount, [null]);
    }
  }
};
TActiveTraceHistogram.prototype = {};
TActiveTraceHistogram.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I16) {
        this.version = input.readI16().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.histogramSchemaType = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.LIST) {
        var _size24 = 0;
        var _rtmp328;
        this.activeTraceCount = [];
        var _etype27 = 0;
        _rtmp328 = input.readListBegin();
        _etype27 = _rtmp328.etype;
        _size24 = _rtmp328.size;
        for (var _i29 = 0; _i29 < _size24; ++_i29)
        {
          var elem30 = null;
          elem30 = input.readI32().value;
          this.activeTraceCount.push(elem30);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TActiveTraceHistogram.prototype.write = function(output) {
  output.writeStructBegin('TActiveTraceHistogram');
  if (this.version !== null && this.version !== undefined) {
    output.writeFieldBegin('version', Thrift.Type.I16, 1);
    output.writeI16(this.version);
    output.writeFieldEnd();
  }
  if (this.histogramSchemaType !== null && this.histogramSchemaType !== undefined) {
    output.writeFieldBegin('histogramSchemaType', Thrift.Type.I32, 2);
    output.writeI32(this.histogramSchemaType);
    output.writeFieldEnd();
  }
  if (this.activeTraceCount !== null && this.activeTraceCount !== undefined) {
    output.writeFieldBegin('activeTraceCount', Thrift.Type.LIST, 3);
    output.writeListBegin(Thrift.Type.I32, this.activeTraceCount.length);
    for (var iter31 in this.activeTraceCount)
    {
      if (this.activeTraceCount.hasOwnProperty(iter31))
      {
        iter31 = this.activeTraceCount[iter31];
        output.writeI32(iter31);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TActiveTrace = function(args) {
  this.histogram = null;
  if (args) {
    if (args.histogram !== undefined && args.histogram !== null) {
      this.histogram = new TActiveTraceHistogram(args.histogram);
    }
  }
};
TActiveTrace.prototype = {};
TActiveTrace.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.histogram = new TActiveTraceHistogram();
        this.histogram.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TActiveTrace.prototype.write = function(output) {
  output.writeStructBegin('TActiveTrace');
  if (this.histogram !== null && this.histogram !== undefined) {
    output.writeFieldBegin('histogram', Thrift.Type.STRUCT, 1);
    this.histogram.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TResponseTime = function(args) {
  this.avg = 0;
  this.max = 0;
  if (args) {
    if (args.avg !== undefined && args.avg !== null) {
      this.avg = args.avg;
    }
    if (args.max !== undefined && args.max !== null) {
      this.max = args.max;
    }
  }
};
TResponseTime.prototype = {};
TResponseTime.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I64) {
        this.avg = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.max = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TResponseTime.prototype.write = function(output) {
  output.writeStructBegin('TResponseTime');
  if (this.avg !== null && this.avg !== undefined) {
    output.writeFieldBegin('avg', Thrift.Type.I64, 1);
    output.writeI64(this.avg);
    output.writeFieldEnd();
  }
  if (this.max !== null && this.max !== undefined) {
    output.writeFieldBegin('max', Thrift.Type.I64, 2);
    output.writeI64(this.max);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TDeadlock = function(args) {
  this.deadlockedThreadCount = null;
  this.deadlockedThreadList = null;
  if (args) {
    if (args.deadlockedThreadCount !== undefined && args.deadlockedThreadCount !== null) {
      this.deadlockedThreadCount = args.deadlockedThreadCount;
    }
    if (args.deadlockedThreadList !== undefined && args.deadlockedThreadList !== null) {
      this.deadlockedThreadList = Thrift.copyList(args.deadlockedThreadList, [TThreadDump]);
    }
  }
};
TDeadlock.prototype = {};
TDeadlock.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.deadlockedThreadCount = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.LIST) {
        var _size32 = 0;
        var _rtmp336;
        this.deadlockedThreadList = [];
        var _etype35 = 0;
        _rtmp336 = input.readListBegin();
        _etype35 = _rtmp336.etype;
        _size32 = _rtmp336.size;
        for (var _i37 = 0; _i37 < _size32; ++_i37)
        {
          var elem38 = null;
          elem38 = new TThreadDump();
          elem38.read(input);
          this.deadlockedThreadList.push(elem38);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TDeadlock.prototype.write = function(output) {
  output.writeStructBegin('TDeadlock');
  if (this.deadlockedThreadCount !== null && this.deadlockedThreadCount !== undefined) {
    output.writeFieldBegin('deadlockedThreadCount', Thrift.Type.I32, 1);
    output.writeI32(this.deadlockedThreadCount);
    output.writeFieldEnd();
  }
  if (this.deadlockedThreadList !== null && this.deadlockedThreadList !== undefined) {
    output.writeFieldBegin('deadlockedThreadList', Thrift.Type.LIST, 2);
    output.writeListBegin(Thrift.Type.STRUCT, this.deadlockedThreadList.length);
    for (var iter39 in this.deadlockedThreadList)
    {
      if (this.deadlockedThreadList.hasOwnProperty(iter39))
      {
        iter39 = this.deadlockedThreadList[iter39];
        iter39.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TAgentStat = function(args) {
  this.agentId = null;
  this.startTimestamp = null;
  this.timestamp = null;
  this.collectInterval = null;
  this.gc = null;
  this.cpuLoad = null;
  this.transaction = null;
  this.activeTrace = null;
  this.dataSourceList = null;
  this.responseTime = null;
  this.deadlock = null;
  this.fileDescriptor = null;
  this.directBuffer = null;
  this.metadata = null;
  if (args) {
    if (args.agentId !== undefined && args.agentId !== null) {
      this.agentId = args.agentId;
    }
    if (args.startTimestamp !== undefined && args.startTimestamp !== null) {
      this.startTimestamp = args.startTimestamp;
    }
    if (args.timestamp !== undefined && args.timestamp !== null) {
      this.timestamp = args.timestamp;
    }
    if (args.collectInterval !== undefined && args.collectInterval !== null) {
      this.collectInterval = args.collectInterval;
    }
    if (args.gc !== undefined && args.gc !== null) {
      this.gc = new TJvmGc(args.gc);
    }
    if (args.cpuLoad !== undefined && args.cpuLoad !== null) {
      this.cpuLoad = new TCpuLoad(args.cpuLoad);
    }
    if (args.transaction !== undefined && args.transaction !== null) {
      this.transaction = new TTransaction(args.transaction);
    }
    if (args.activeTrace !== undefined && args.activeTrace !== null) {
      this.activeTrace = new TActiveTrace(args.activeTrace);
    }
    if (args.dataSourceList !== undefined && args.dataSourceList !== null) {
      this.dataSourceList = new TDataSourceList(args.dataSourceList);
    }
    if (args.responseTime !== undefined && args.responseTime !== null) {
      this.responseTime = new TResponseTime(args.responseTime);
    }
    if (args.deadlock !== undefined && args.deadlock !== null) {
      this.deadlock = new TDeadlock(args.deadlock);
    }
    if (args.fileDescriptor !== undefined && args.fileDescriptor !== null) {
      this.fileDescriptor = new TFileDescriptor(args.fileDescriptor);
    }
    if (args.directBuffer !== undefined && args.directBuffer !== null) {
      this.directBuffer = new TDirectBuffer(args.directBuffer);
    }
    if (args.metadata !== undefined && args.metadata !== null) {
      this.metadata = args.metadata;
    }
  }
};
TAgentStat.prototype = {};
TAgentStat.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.agentId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.startTimestamp = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I64) {
        this.timestamp = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I64) {
        this.collectInterval = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 10:
      if (ftype == Thrift.Type.STRUCT) {
        this.gc = new TJvmGc();
        this.gc.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 20:
      if (ftype == Thrift.Type.STRUCT) {
        this.cpuLoad = new TCpuLoad();
        this.cpuLoad.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 30:
      if (ftype == Thrift.Type.STRUCT) {
        this.transaction = new TTransaction();
        this.transaction.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 40:
      if (ftype == Thrift.Type.STRUCT) {
        this.activeTrace = new TActiveTrace();
        this.activeTrace.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 50:
      if (ftype == Thrift.Type.STRUCT) {
        this.dataSourceList = new TDataSourceList();
        this.dataSourceList.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 60:
      if (ftype == Thrift.Type.STRUCT) {
        this.responseTime = new TResponseTime();
        this.responseTime.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 70:
      if (ftype == Thrift.Type.STRUCT) {
        this.deadlock = new TDeadlock();
        this.deadlock.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 80:
      if (ftype == Thrift.Type.STRUCT) {
        this.fileDescriptor = new TFileDescriptor();
        this.fileDescriptor.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 90:
      if (ftype == Thrift.Type.STRUCT) {
        this.directBuffer = new TDirectBuffer();
        this.directBuffer.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 200:
      if (ftype == Thrift.Type.STRING) {
        this.metadata = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TAgentStat.prototype.write = function(output) {
  output.writeStructBegin('TAgentStat');
  if (this.agentId !== null && this.agentId !== undefined) {
    output.writeFieldBegin('agentId', Thrift.Type.STRING, 1);
    output.writeString(this.agentId);
    output.writeFieldEnd();
  }
  if (this.startTimestamp !== null && this.startTimestamp !== undefined) {
    output.writeFieldBegin('startTimestamp', Thrift.Type.I64, 2);
    output.writeI64(this.startTimestamp);
    output.writeFieldEnd();
  }
  if (this.timestamp !== null && this.timestamp !== undefined) {
    output.writeFieldBegin('timestamp', Thrift.Type.I64, 3);
    output.writeI64(this.timestamp);
    output.writeFieldEnd();
  }
  if (this.collectInterval !== null && this.collectInterval !== undefined) {
    output.writeFieldBegin('collectInterval', Thrift.Type.I64, 4);
    output.writeI64(this.collectInterval);
    output.writeFieldEnd();
  }
  if (this.gc !== null && this.gc !== undefined) {
    output.writeFieldBegin('gc', Thrift.Type.STRUCT, 10);
    this.gc.write(output);
    output.writeFieldEnd();
  }
  if (this.cpuLoad !== null && this.cpuLoad !== undefined) {
    output.writeFieldBegin('cpuLoad', Thrift.Type.STRUCT, 20);
    this.cpuLoad.write(output);
    output.writeFieldEnd();
  }
  if (this.transaction !== null && this.transaction !== undefined) {
    output.writeFieldBegin('transaction', Thrift.Type.STRUCT, 30);
    this.transaction.write(output);
    output.writeFieldEnd();
  }
  if (this.activeTrace !== null && this.activeTrace !== undefined) {
    output.writeFieldBegin('activeTrace', Thrift.Type.STRUCT, 40);
    this.activeTrace.write(output);
    output.writeFieldEnd();
  }
  if (this.dataSourceList !== null && this.dataSourceList !== undefined) {
    output.writeFieldBegin('dataSourceList', Thrift.Type.STRUCT, 50);
    this.dataSourceList.write(output);
    output.writeFieldEnd();
  }
  if (this.responseTime !== null && this.responseTime !== undefined) {
    output.writeFieldBegin('responseTime', Thrift.Type.STRUCT, 60);
    this.responseTime.write(output);
    output.writeFieldEnd();
  }
  if (this.deadlock !== null && this.deadlock !== undefined) {
    output.writeFieldBegin('deadlock', Thrift.Type.STRUCT, 70);
    this.deadlock.write(output);
    output.writeFieldEnd();
  }
  if (this.fileDescriptor !== null && this.fileDescriptor !== undefined) {
    output.writeFieldBegin('fileDescriptor', Thrift.Type.STRUCT, 80);
    this.fileDescriptor.write(output);
    output.writeFieldEnd();
  }
  if (this.directBuffer !== null && this.directBuffer !== undefined) {
    output.writeFieldBegin('directBuffer', Thrift.Type.STRUCT, 90);
    this.directBuffer.write(output);
    output.writeFieldEnd();
  }
  if (this.metadata !== null && this.metadata !== undefined) {
    output.writeFieldBegin('metadata', Thrift.Type.STRING, 200);
    output.writeString(this.metadata);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TAgentStatBatch = function(args) {
  this.agentId = null;
  this.startTimestamp = null;
  this.agentStats = null;
  if (args) {
    if (args.agentId !== undefined && args.agentId !== null) {
      this.agentId = args.agentId;
    }
    if (args.startTimestamp !== undefined && args.startTimestamp !== null) {
      this.startTimestamp = args.startTimestamp;
    }
    if (args.agentStats !== undefined && args.agentStats !== null) {
      this.agentStats = Thrift.copyList(args.agentStats, [TAgentStat]);
    }
  }
};
TAgentStatBatch.prototype = {};
TAgentStatBatch.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.agentId = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.startTimestamp = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 10:
      if (ftype == Thrift.Type.LIST) {
        var _size40 = 0;
        var _rtmp344;
        this.agentStats = [];
        var _etype43 = 0;
        _rtmp344 = input.readListBegin();
        _etype43 = _rtmp344.etype;
        _size40 = _rtmp344.size;
        for (var _i45 = 0; _i45 < _size40; ++_i45)
        {
          var elem46 = null;
          elem46 = new TAgentStat();
          elem46.read(input);
          this.agentStats.push(elem46);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TAgentStatBatch.prototype.write = function(output) {
  output.writeStructBegin('TAgentStatBatch');
  if (this.agentId !== null && this.agentId !== undefined) {
    output.writeFieldBegin('agentId', Thrift.Type.STRING, 1);
    output.writeString(this.agentId);
    output.writeFieldEnd();
  }
  if (this.startTimestamp !== null && this.startTimestamp !== undefined) {
    output.writeFieldBegin('startTimestamp', Thrift.Type.I64, 2);
    output.writeI64(this.startTimestamp);
    output.writeFieldEnd();
  }
  if (this.agentStats !== null && this.agentStats !== undefined) {
    output.writeFieldBegin('agentStats', Thrift.Type.LIST, 10);
    output.writeListBegin(Thrift.Type.STRUCT, this.agentStats.length);
    for (var iter47 in this.agentStats)
    {
      if (this.agentStats.hasOwnProperty(iter47))
      {
        iter47 = this.agentStats[iter47];
        iter47.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TDataSource = function(args) {
  this.id = null;
  this.serviceTypeCode = null;
  this.databaseName = null;
  this.url = null;
  this.activeConnectionSize = 0;
  this.maxConnectionSize = null;
  if (args) {
    if (args.id !== undefined && args.id !== null) {
      this.id = args.id;
    }
    if (args.serviceTypeCode !== undefined && args.serviceTypeCode !== null) {
      this.serviceTypeCode = args.serviceTypeCode;
    }
    if (args.databaseName !== undefined && args.databaseName !== null) {
      this.databaseName = args.databaseName;
    }
    if (args.url !== undefined && args.url !== null) {
      this.url = args.url;
    }
    if (args.activeConnectionSize !== undefined && args.activeConnectionSize !== null) {
      this.activeConnectionSize = args.activeConnectionSize;
    }
    if (args.maxConnectionSize !== undefined && args.maxConnectionSize !== null) {
      this.maxConnectionSize = args.maxConnectionSize;
    }
  }
};
TDataSource.prototype = {};
TDataSource.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.id = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I16) {
        this.serviceTypeCode = input.readI16().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.databaseName = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.url = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.I32) {
        this.activeConnectionSize = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.I32) {
        this.maxConnectionSize = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TDataSource.prototype.write = function(output) {
  output.writeStructBegin('TDataSource');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.I32, 1);
    output.writeI32(this.id);
    output.writeFieldEnd();
  }
  if (this.serviceTypeCode !== null && this.serviceTypeCode !== undefined) {
    output.writeFieldBegin('serviceTypeCode', Thrift.Type.I16, 2);
    output.writeI16(this.serviceTypeCode);
    output.writeFieldEnd();
  }
  if (this.databaseName !== null && this.databaseName !== undefined) {
    output.writeFieldBegin('databaseName', Thrift.Type.STRING, 3);
    output.writeString(this.databaseName);
    output.writeFieldEnd();
  }
  if (this.url !== null && this.url !== undefined) {
    output.writeFieldBegin('url', Thrift.Type.STRING, 4);
    output.writeString(this.url);
    output.writeFieldEnd();
  }
  if (this.activeConnectionSize !== null && this.activeConnectionSize !== undefined) {
    output.writeFieldBegin('activeConnectionSize', Thrift.Type.I32, 5);
    output.writeI32(this.activeConnectionSize);
    output.writeFieldEnd();
  }
  if (this.maxConnectionSize !== null && this.maxConnectionSize !== undefined) {
    output.writeFieldBegin('maxConnectionSize', Thrift.Type.I32, 6);
    output.writeI32(this.maxConnectionSize);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TDataSourceList = function(args) {
  this.dataSourceList = null;
  if (args) {
    if (args.dataSourceList !== undefined && args.dataSourceList !== null) {
      this.dataSourceList = Thrift.copyList(args.dataSourceList, [TDataSource]);
    }
  }
};
TDataSourceList.prototype = {};
TDataSourceList.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.LIST) {
        var _size48 = 0;
        var _rtmp352;
        this.dataSourceList = [];
        var _etype51 = 0;
        _rtmp352 = input.readListBegin();
        _etype51 = _rtmp352.etype;
        _size48 = _rtmp352.size;
        for (var _i53 = 0; _i53 < _size48; ++_i53)
        {
          var elem54 = null;
          elem54 = new TDataSource();
          elem54.read(input);
          this.dataSourceList.push(elem54);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TDataSourceList.prototype.write = function(output) {
  output.writeStructBegin('TDataSourceList');
  if (this.dataSourceList !== null && this.dataSourceList !== undefined) {
    output.writeFieldBegin('dataSourceList', Thrift.Type.LIST, 1);
    output.writeListBegin(Thrift.Type.STRUCT, this.dataSourceList.length);
    for (var iter55 in this.dataSourceList)
    {
      if (this.dataSourceList.hasOwnProperty(iter55))
      {
        iter55 = this.dataSourceList[iter55];
        iter55.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TFileDescriptor = function(args) {
  this.openFileDescriptorCount = null;
  if (args) {
    if (args.openFileDescriptorCount !== undefined && args.openFileDescriptorCount !== null) {
      this.openFileDescriptorCount = args.openFileDescriptorCount;
    }
  }
};
TFileDescriptor.prototype = {};
TFileDescriptor.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I64) {
        this.openFileDescriptorCount = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TFileDescriptor.prototype.write = function(output) {
  output.writeStructBegin('TFileDescriptor');
  if (this.openFileDescriptorCount !== null && this.openFileDescriptorCount !== undefined) {
    output.writeFieldBegin('openFileDescriptorCount', Thrift.Type.I64, 1);
    output.writeI64(this.openFileDescriptorCount);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

module.exports = {
 TAgentInfo
}
