'use strict'

const PacketType = {
  APPLICATION_SEND : 1,
  APPLICATION_TRACE_SEND : 2,
  APPLICATION_TRACE_SEND_ACK : 3,
  APPLICATION_REQUEST: 5,
  APPLICATION_RESPONSE: 6,

  APPLICATION_STREAM_CREATE: 10,
  APPLICATION_STREAM_CREATE_SUCCESS: 12,
  APPLICATION_STREAM_CREATE_FAIL: 14,

  APPLICATION_STREAM_CLOSE: 15,

  APPLICATION_STREAM_PING: 17,
  APPLICATION_STREAM_PONG: 18,

  APPLICATION_STREAM_RESPONSE: 20,

  CONTROL_CLIENT_CLOSE: 100,
  CONTROL_SERVER_CLOSE: 110,

  // control packet
  CONTROL_HANDSHAKE: 150,
  CONTROL_HANDSHAKE_RESPONSE: 151,

  // keep stay because of performance in case of ping and pong. others removed.
  // CONTROL_PING will be deprecated. caused : Two payload types are used in one control packet.
  // since 1.7.0, use CONTROL_PING_SIMPLE, CONTROL_PING_PAYLOAD
  CONTROL_PING: 200,
  CONTROL_PONG: 201,

  CONTROL_PING_SIMPLE: 210,
  CONTROL_PING_PAYLOAD: 211,

  UNKNOWN: 500,
}

module.exports = {
  PacketType
}
