'use strict'

const PacketType = {
  APPLICATION_SEND : 1,
  APPLICATION_TRACE_SEND : 2,
  APPLICATION_TRACE_SEND_ACK : 3,
  APPLICATION_REQUEST : 5,
  APPLICATION_RESPONSE : 6,
  CONTROL_HANDSHAKE: 150,
  CONTROL_HANDSHAKE_RESPONSE: 151,
  CONTROL_PING_PAYLOAD : 211,
}

module.exports = {
  PacketType
}
