const PacketType = {
  APPLICATION_SEND : 1,
  APPLICATION_TRACE_SEND : 2,
  APPLICATION_TRACE_SEND_ACK : 3,
  APPLICATION_REQUEST : 5,
  APPLICATION_RESPONSE : 6,
}

module.exports = {
  PacketType
}