name: CI

on: [push, pull_request]

env:
  TARGET_NODE_VERSION: '22'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    strategy:
      matrix:
        node_version:
          - 18
          - 20
          - 22

    name: Node ${{ matrix.node_version }} on ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm install
      - run: npm test
      - name: Lint
        if: matrix.node_version == env.TARGET_NODE_VERSION
        run: npm run lint
      - name: Report checkstyle
        if: matrix.node_version == env.TARGET_NODE_VERSION
        continue-on-error: true
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/report-checkstyle.js')
            await script({ github, context })
      - name: Coverage
        if: matrix.node_version == env.TARGET_NODE_VERSION
        run: npm run coverage
      - name: Setup LCOV
        if: matrix.node_version == env.TARGET_NODE_VERSION
        uses: hrishikesh-kadam/setup-lcov@v1
        with:
          ref: v1.16
      - name: Report code coverage
        if: matrix.node_version == env.TARGET_NODE_VERSION
        continue-on-error: true
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: coverage/lcov.info
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
