name: Report Checkstyle

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  report:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      checks: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Download checkstyle artifact
        uses: actions/download-artifact@v4
        with:
          name: checkstyle-result
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Report checkstyle
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/report-checkstyle.js')
            await script({ github, context })
