name: Report Checkstyle

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  report:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      checks: write
    steps:
      - name: Download checkstyle artifact
        uses: actions/download-artifact@v4
        with:
          name: checkstyle-result
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload checkstyle report
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: 'checkstyle-result.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
